import { StyleSheet } from 'react-native';
import { MeshitimeColors } from '@/theme/meshitime-theme';


export const styles=StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F3F4F6',
  },
  mapBase: {
    flex: 1,
    backgroundColor: '#F2F0EA',
  },
  gridOverlay: {
    ...StyleSheet.absoluteFill,
    opacity: 0.18,
    backgroundColor: 'transparent',
    borderWidth: 0,
  },
  streetHorizontal: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 3,
    backgroundColor: '#D1D5DB',
  },
  streetVertical: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 3,
    backgroundColor: '#D1D5DB',
  },
  pinWrapper: {
    position: 'absolute',
    transform: [{ translateX: -20 }, { translateY: -40 }],
  },
  pin: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: MeshitimeColors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pinInactive: {
    backgroundColor: '#9CA3AF',
  },
  pinText: {
    fontSize: 20,
  },
  searchBox: {
    position: 'absolute',
    top: 40,
    left: 12,
    right: 12,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    minHeight: 48,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: MeshitimeColors.text,
  },
  filterScroll: {
    position: 'absolute',
    top: 100,
    left: 0,
    right: 0,
    maxHeight: 46,
  },
  filterContent: {
    paddingHorizontal: 12,
    gap: 8,
  },
  filterChip: {
    minHeight: 34,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.94)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  filterChipActive: {
    backgroundColor: MeshitimeColors.primary,
  },
  filterText: {
    color: '#374151',
    fontSize: 13,
    fontWeight: '700',
  },
  filterTextActive: {
    color: '#FFFFFF',
  },
  bottomPeek: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.96)',
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  peekHandle: {
    alignSelf: 'center',
    width: 44,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#D1D5DB',
    marginBottom: 16,
  },
  peekTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: MeshitimeColors.text,
  },
  peekSubtitle: {
    marginTop: 2,
    color: MeshitimeColors.textMuted,
    fontSize: 13,
  },
  bottomActions: {
    marginTop: 12,
    flexDirection: 'row',
    gap: 10,
  },
  bottomActionButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomActionText: {
    color: '#374151',
    fontSize: 13,
    fontWeight: '700',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFill,
    backgroundColor: MeshitimeColors.overlay,
  },
  modalCard: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '78%',
    overflow: 'hidden',
  },
  modalImageWrap: {
    marginHorizontal: 16,
    borderRadius: 18,
    overflow: 'hidden',
  },
  modalImage: {
    width: '100%',
    height: 180,
  },
  discountBadge: {
    position: 'absolute',
    right: 10,
    top: 10,
    backgroundColor: MeshitimeColors.primary,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  discountText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 13,
  },
  modalBody: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    gap: 10,
  },
  modalTitle: {
    fontSize: 22,
    color: MeshitimeColors.text,
    fontWeight: '800',
  },
  modalMeta: {
    color: MeshitimeColors.textMuted,
    fontSize: 14,
  },
  modalPrice: {
    color: MeshitimeColors.primary,
    fontWeight: '800',
    fontSize: 20,
  },
  modalOriginalPrice: {
    textDecorationLine: 'line-through',
    color: '#9CA3AF',
    fontSize: 14,
  },
  modalButtons: {
    marginTop: 8,
    flexDirection: 'row',
    gap: 10,
  },
  secondaryCta: {
    flex: 1,
    minHeight: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    justifyContent: 'center',
    alignItems: 'center',
  },
  secondaryCtaText: {
    color: '#4B5563',
    fontWeight: '700',
  },
  primaryCta: {
    flex: 1,
    minHeight: 48,
    borderRadius: 12,
    backgroundColor: MeshitimeColors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  primaryCtaText: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  backToMyLocationButton: {
    position: 'absolute',
    right: 16,
    bottom: 130,
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOpacity: 0.14,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    elevation: 5,
  },
  backToMyLocationButtonDisabled: {
    opacity: 0.7,
  },
});