import { StyleSheet } from "react-native";
import { MeshitimeColors } from "@/theme/meshitime-theme";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: MeshitimeColors.background,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingBottom: 32,
  },
  pageHeader: {
    marginTop: 8,
    marginBottom: 16,
  },
  pageTitle: {
    fontSize: 26,
    fontWeight: "800",
    color: MeshitimeColors.text,
  },
  pageSubtitle: {
    marginTop: 4,
    fontSize: 14,
    color: MeshitimeColors.textMuted,
  },
  sectionCard: {
    backgroundColor: MeshitimeColors.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: MeshitimeColors.border,
    padding: 16,
    marginBottom: 14,
  },
  summaryCard: {
    backgroundColor: MeshitimeColors.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: MeshitimeColors.border,
    padding: 16,
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: MeshitimeColors.text,
    marginBottom: 12,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: MeshitimeColors.textMuted,
    marginBottom: 6,
  },
  requiredMark: {
    color: MeshitimeColors.primary,
    fontWeight: "700",
  },
  input: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: MeshitimeColors.border,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: MeshitimeColors.text,
  },
  textArea: {
    minHeight: 88,
    textAlignVertical: "top",
  },
  helperText: {
    marginTop: 6,
    fontSize: 12,
    color: MeshitimeColors.textMuted,
  },
  row: {
    flexDirection: "row",
    gap: 10,
  },
  rowItem: {
    flex: 1,
  },
  priceInputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  priceSuffix: {
    fontSize: 14,
    fontWeight: "700",
    color: MeshitimeColors.textMuted,
  },
  discountPreview: {
    marginTop: 8,
    fontSize: 13,
    fontWeight: "700",
    color: MeshitimeColors.primary,
  },
  chipWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 18,
    backgroundColor: "#F3F4F6",
    borderWidth: 1,
    borderColor: MeshitimeColors.border,
  },
  chipSelected: {
    backgroundColor: "#FEE2E2",
    borderColor: MeshitimeColors.primary,
  },
  chipText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#374151",
  },
  chipTextSelected: {
    color: MeshitimeColors.primary,
  },
  imagePicker: {
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: MeshitimeColors.border,
    borderRadius: 14,
    minHeight: 160,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FAFAFA",
    overflow: "hidden",
  },
  imagePickerFilled: {
    borderStyle: "solid",
    padding: 0,
  },
  imagePickerIcon: {
    fontSize: 28,
    marginBottom: 6,
  },
  imagePickerText: {
    fontSize: 14,
    fontWeight: "700",
    color: MeshitimeColors.text,
  },
  imagePickerHint: {
    marginTop: 4,
    fontSize: 12,
    color: MeshitimeColors.textMuted,
  },
  previewImage: {
    width: "100%",
    height: 180,
  },
  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  toggleLabelWrap: {
    flex: 1,
    paddingRight: 12,
  },
  toggleLabel: {
    fontSize: 15,
    fontWeight: "700",
    color: MeshitimeColors.text,
  },
  toggleHint: {
    marginTop: 2,
    fontSize: 12,
    color: MeshitimeColors.textMuted,
  },
  buttonRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 8,
  },
  primaryButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 12,
    backgroundColor: MeshitimeColors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontWeight: "800",
    fontSize: 15,
  },
  secondaryButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: MeshitimeColors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryButtonText: {
    color: MeshitimeColors.text,
    fontWeight: "700",
    fontSize: 15,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  summaryLabel: {
    width: 110,
    fontSize: 13,
    fontWeight: "700",
    color: MeshitimeColors.textMuted,
  },
  summaryValue: {
    flex: 1,
    fontSize: 14,
    fontWeight: "600",
    color: MeshitimeColors.text,
    textAlign: "right",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "center",
    padding: 24,
  },
  modalCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 20,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: MeshitimeColors.text,
  },
  modalMessage: {
    marginTop: 8,
    fontSize: 14,
    color: MeshitimeColors.textMuted,
  },
  modalButtonRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 18,
  },
  modalPrimaryButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: MeshitimeColors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  modalPrimaryButtonText: {
    color: "#FFFFFF",
    fontWeight: "800",
  },
  modalSecondaryButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: "#F3F4F6",
    alignItems: "center",
    justifyContent: "center",
  },
  modalSecondaryButtonText: {
    color: MeshitimeColors.text,
    fontWeight: "700",
  },
  heroPreview: {
    height: 140,
    borderRadius: 16,
    overflow: "hidden",
    marginBottom: 14,
    backgroundColor: "#FEE2E2",
    alignItems: "center",
    justifyContent: "center",
  },
  heroImage: {
    width: "100%",
    height: "100%",
  },
  dealCard: {
    backgroundColor: MeshitimeColors.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: MeshitimeColors.border,
    padding: 14,
    marginBottom: 14,
  },
  dealTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: MeshitimeColors.text,
  },
  dealMeta: {
    marginTop: 6,
    fontSize: 13,
    color: MeshitimeColors.textMuted,
  },
  dealPriceRow: {
    marginTop: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  dealOriginal: {
    fontSize: 13,
    color: "#9CA3AF",
    textDecorationLine: "line-through",
  },
  dealPrice: {
    fontSize: 20,
    fontWeight: "800",
    color: MeshitimeColors.primary,
  },
  dealBadge: {
    alignSelf: "flex-start",
    marginTop: 10,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: "#FEE2E2",
  },
  dealBadgeText: {
    fontSize: 12,
    fontWeight: "800",
    color: MeshitimeColors.primary,
  },
});
